<?php echo $this->doctype() ?>

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Zend Framework Quickstart Application</title>
  <?php echo $this->headLink()->appendStylesheet('/css/site.css') ?>
</head>
<body>
<div id="wrap">
	<div id="logo">	    
	        ZF Quickstart Application      
	</div>
	<div id="page">
		<div id="menu">
			<h1>Menu List</h1>			
			<ul>
				<li>
					<a href="<?=$this->url(array('controller'=>'index'), 'default', true)?>">HOME</a>				
				</li>
				<li>
					<a href="<?php 
	        			echo $this->url(array('controller'=>'guestbook'), 'default', true);
	        		?>">Guestbook</a>
	        	</li>
				<li>
					<a href="<?php 
	        			echo $this->url(array('controller'=>'album', 'action'=>'index'));
	        		?>">Album List</a>
	        	</li>
			</ul>
		</div>
	
		<div id="contents">
			<h2>Page Title : </h2>
		    <h1><?php echo $this->escape($this->title); ?></h1>
		<?php echo $this->layout()->content; ?>
		</div>
	</div>
	<div id="footer">
		Footer area
	</div>
</div>
</body>
</html>